### ISSUE TITLE
Plugin stopped displaying country flags for clans

### ISSUE THREAD

**Issue by YvesW** [melkypie/ClanChatCountryFlags#7]
Since today, the plugin stopped displaying country flags for my CC. It still works in the FC.

The problem persists after restarting RL. client.log doesn't contain any mentions of clan-chat-country-flags except the ExternalPluginManager loading it.

FC:
![afbeelding](https://user-images.githubusercontent.com/7929021/178071168-33995264-3b1b-4c3d-9251-0c20a9b70017.png)

CC:
![afbeelding](https://user-images.githubusercontent.com/7929021/178071191-437d1741-93b0-48a7-9f45-2ade7dd60ac3.png)

**Comment by YvesW** [comment]
And now they're suddenly back. I'm very sorry; I'm not sure what is causing this behavior. Only thing I can think off right now is that Jagex screwed a lot with the widget IDs in the last patch.

**Comment by YvesW** [comment]
And... they're gone again. Not sure what is exactly causing this.

**Comment by F-Lambda** [comment]
Can confirm that they're still not present in clan chats

**Comment by YvesW** [comment]
Getting this accompanying error right now while testing my own plugins with pluginhub enabled:
`[Client] WARN  n.runelite.client.eventbus.EventBus - Uncaught exception in event subscriber
java.lang.NumberFormatException: For input string: "easelheart"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
	at java.base/java.lang.Integer.parseInt(Integer.java:668)
	at java.base/java.lang.Integer.parseInt(Integer.java:786)
	at melky.worldflags.WorldFlagsPlugin.changeWorldsToFlags(WorldFlagsPlugin.java:225)
	at melky.worldflags.WorldFlagsPlugin.toggleWorldsToFlags(WorldFlagsPlugin.java:205)
	at melky.worldflags.WorldFlagsPlugin.toggleWorldsToFlags(WorldFlagsPlugin.java:172)
	at melky.worldflags.WorldFlagsPlugin.lambda$onScriptPostFired$6(WorldFlagsPlugin.java:140)
	at net.runelite.client.callback.ClientThread.lambda$invoke$0(ClientThread.java:49)
	at net.runelite.client.callback.ClientThread.invoke(ClientThread.java:62)
	at net.runelite.client.callback.ClientThread.invoke(ClientThread.java:47)
	at melky.worldflags.WorldFlagsPlugin.onScriptPostFired(WorldFlagsPlugin.java:140)
	at net.runelite.client.eventbus.EventBus$Subscriber.invoke(EventBus.java:70)
	at net.runelite.client.eventbus.EventBus.post(EventBus.java:223)
	at net.runelite.client.callback.Hooks.post(Hooks.java:189)
	at client.me(client.java:7237)
	at du.e(du.java:62413)
	at fm.h(fm.java:113)
	at client.gg(client.java:3168)
	at client.an(client.java:1119)
	at an.ao(an.java:390)
	at an.run(an.java:369)
	at java.base/java.lang.Thread.run(Thread.java:833)`
His name is Weaselheart. Without checking the code, I guess it's getting the wrong Widget (names instead of worlds) or it just matches anything that starts with a "W", and thus removes the first letter of the name (instead of the "W" of the world). Converting that string to an int results in a NumberFormatException.
